# Generated by Django 4.1 on 2022-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='about',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
