# Generated by Django 4.0.4 on 2022-07-11 05:05

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/', validators=[base.validators.img__size])),
                ('birthday', models.DateTimeField(blank=True)),
                ('about', models.TextField(max_length=1000)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('vk', models.URLField(blank=True, null=True)),
                ('reddit', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
