# Generated by Django 4.1 on 2022-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profileuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
