# Generated by Django 4.0.4 on 2022-07-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profileuser_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profileuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profileuser'),
        ),
    ]
