# Generated by Django 4.0.4 on 2022-07-11 11:59

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_profile_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/', validators=[base.validators.img__size]),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(null=True, upload_to='static/images', validators=[base.validators.story_size]),
        ),
    ]
