# Generated by Django 4.0.4 on 2022-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_image_alter_story_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
